- name: Send notification message via Slack
  local_action:
    module: slack
    domain: "{{ laclasse_slack.host }}"
    token: "{{ laclasse_slack.token }}"
    msg: "3...2...1... backend for {{ backend }} v{{ 'laclasse_' + backend + '_version' }} @ {{ inventory_hostname }} :rocket: "
    channel: "{{ laclasse_slack.channel }}"
  ignore_errors: true
  tags:
    - laclasse
    - laclasse:backend

- include: backend.yml tags=laclasse,laclasse:backend,nginx
  when: laclasse_loadbalancers is defined and laclasse_loadbalancers|count > 0

