- name: Restart frontend nginx
  action: service name=nginx state=restarted
  delegate_to: "{{ item }}"
  with_items: laclasse_loadbalancers
  tags:
    - laclasse:backend
    - laclasse

- name: Send notification message via Slack
  local_action:
    module: slack
    domain: "{{ laclasse_slack.host }}"
    token: "{{ laclasse_slack.token }}"
    msg: "Backend {{ inventory_hostname }} successfully added to frontends for {{ backend }} :thumbsup:"
    channel: "{{ laclasse_slack.channel }}"
  tags:
    - laclasse:backend
    - laclasse
